[package]
name = "document-verification-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.document-verification]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.63.2"
default-features = false
